from __future__ import annotations

from datetime import datetime
from pathlib import Path
import shutil
import subprocess
import textwrap


BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "Global Resume"
SOURCE_DATA_FILE = BASE_DIR / "resume-source-data.md"
SCREENING_ANSWERS_SOURCE_FILE = BASE_DIR / "global_resume_screening_answers.md"
REFERENCE_DOC_FILE = BASE_DIR / "resume-template.docx"


README_CONTENT = """
# Global Resume Package

This folder contains a job application package built for AI job agents and ATS systems.

Goal:
- Give agents a strong, truthful package they can use quickly.
- Keep everything grounded in verified source material.
- Avoid making up metrics, technologies, dates, or claims.

Files:
- `global_resume.md` - comprehensive master resume for broad job matching
- `candidate_profile.md` - structured profile for application forms and recruiter summaries
- `application_agent_instructions.md` - rules for any AI system using this package
- `screening_answers.md` - truthful screening and application answer bank
- `verified_source_data.md` - detailed factual source material copied from the workspace source file
- `global_resume.docx` - Word export if Pandoc is available on this machine

How to use:
1. Upload `global_resume.md` or `global_resume.docx` as the main resume.
2. Give AI agents `candidate_profile.md`, `screening_answers.md`, and `application_agent_instructions.md`.
3. Keep `verified_source_data.md` available as a fallback fact sheet.
4. Use the selected personal projects section when a role values product initiative, AI-assisted engineering, or OpenAI API work.

Generation:
- This folder is generated by `create_global_resume.py`.
- Last generated: {generated_at}
""".strip()


GLOBAL_RESUME_CONTENT = """
# Candidate Name
City, State | phone@example.com | email@example.com
LinkedIn: https://linkedin.com/in/example | GitHub: https://github.com/example

## Executive Summary
- Replace this template with a broad, truthful summary of the candidate.
- Keep the content general enough for wide job matching while staying factual.
- Focus on the strongest repeatable themes from verified experience.

## Core Competencies
- Core competency 1
- Core competency 2
- Core competency 3
- Core competency 4
- Core competency 5

## Professional Experience

**Company Name** | City, State
**Role Title** | 2021 - Present
- Replace with truthful achievements grounded in verified source data.
- Prefer impact, ownership, and relevant technical detail.

**Company Name** | City, State
**Role Title** | 2018 - 2021
- Replace with truthful achievements grounded in verified source data.
- Keep bullets concise and ATS-friendly.

## Selected Personal Projects

**Project Name** | Personal Project
- Replace with a project that strengthens the candidate's positioning.

## Technical Skills
- Core:
- Strong:
- Working:

## Education
- Degree
- School | Year

## Certifications
- Certification | Year
""".strip()


CANDIDATE_PROFILE_CONTENT = """
# Candidate Profile

## Snapshot
- Name:
- Location:
- Remote:
- Contact:
- LinkedIn:
- GitHub:
- Experience:

## Best-Fit Role Targets
- Role target 1
- Role target 2
- Role target 3

## Strongest Positioning
- Primary positioning angle
- Secondary positioning angle
- Best-fit seniority
- Strongest evidence themes

## Strongest Technologies
- Technology 1
- Technology 2
- Technology 3

## Industries and System Context
- Industry 1
- Industry 2
- System context 1

## Technical Leadership Signals
- Leadership signal 1
- Leadership signal 2
- Leadership signal 3

## Preferred Search Focus
- Prioritize:
- Favor:
- De-prioritize:

## Location and Work Preferences
- Preferred location:
- Remote preference:
- Hybrid/onsite preference:

## Education and Certifications
- Education item
- Certification item

## Selected Personal Projects
- Project highlight 1
- Project highlight 2

## Application Keywords
- keyword 1
- keyword 2
- keyword 3

## Do Not Misrepresent
- Constraint 1
- Constraint 2
- Constraint 3
""".strip()


AGENT_INSTRUCTIONS_CONTENT = """
# Application Agent Instructions

## Purpose
Use this package to apply the candidate to jobs quickly while staying fully truthful.

## Primary Goal
Maximize the number of strong-fit applications without inventing experience, metrics, technologies, dates, certifications, work authorization details, clearance, or management scope.

## Files To Use
1. `global_resume.md` as the main resume
2. `candidate_profile.md` for role targeting and recruiter summaries
3. `screening_answers.md` for common application questions
4. `verified_source_data.md` when more factual detail is needed

## Hard Rules
- Do not fabricate information
- Do not round unknown facts into confident claims
- Do not add tools or frameworks not supported by source data
- Do not claim formal people management beyond the verified small-team leadership at L & F
- Use `screening_answers.md` for application-form facts such as work authorization, sponsorship, clearance, salary range, start timing, and relocation
- If a form asks for something not covered by the package, flag it for manual review instead of guessing

## Best-Fit Role Families
- Replace with the candidate's best-fit role families.

## Fastest-Match Application Strategy
- Prioritize roles with the strongest direct evidence.
- Prefer job descriptions that clearly match the verified source data.
- Be conservative when claims are not explicitly supported.

## Tailoring Rules
- Reorder bullets and summary emphasis based on the job description
- Keep the strongest relevant achievements near the top.
- Emphasize the candidate's strongest ownership and impact themes.
- Use personal projects only when they strengthen truthful alignment.
- Keep paid professional experience ahead of personal projects unless the role clearly justifies the reverse.

## Roles To Avoid Or De-Prioritize
- Replace with the candidate's actual avoid/de-prioritize list.

## Tone For Recruiter Summaries
- Direct
- Professional
- Grounded
- No hype
- No inflated claims

## If A Form Asks For Information Not In The Package
Stop and flag for manual review rather than guessing.
""".strip()


SCREENING_ANSWERS_FALLBACK_CONTENT = """
# Screening Answers

Use these answers only when they are directly supported by the package. If a field is marked unknown, do not guess.

## Quick Summary
Q: What kind of engineer is the candidate?
A: Replace with a short truthful summary.

Q: How much experience does Rey have?
A: Replace with the verified years of experience.

Q: What roles fit best?
A: Replace with the candidate's best-fit role list.

Q: What are the candidate's strongest technical areas?
A: Replace with verified strengths.

Q: What kinds of systems has Rey worked on?
A: Replace with verified system context.

## Work Style and Leadership
Q: Is the candidate a manager?
A: Replace with a truthful answer.

Q: Does Rey have leadership experience?
A: Replace with verified leadership evidence.

Q: What makes the candidate a strong fit?
A: Replace with verified impact themes.

## Location and Search Preferences
Q: Where is the candidate located?
A: Replace with a verified location.

Q: Is the candidate open to remote roles?
A: Replace with a verified answer.

Q: Is the candidate open to onsite or hybrid roles?
A: Replace with a verified answer.

Q: Is the candidate actively looking?
A: Replace with a verified answer.

## Verified Highlight Answers
Q: What is a strong example of production impact?
A: Replace with a verified example.

Q: What is a strong example of scale?
A: Replace with a verified example.

Q: What is a strong example of architecture or modernization work?
A: Replace with a verified example.

Q: What is a strong example of reporting or dashboard integration?
A: Replace with a verified example.

Q: What is a strong example of Python experience?
A: Replace with a verified example.

## Application Facts
Q: Is the candidate authorized to work in the United States?
A:

Q: Does Rey require employer sponsorship?
A:

Q: Does the candidate hold an active security clearance?
A:

Q: What salary is Rey targeting?
A:

Q: What is Rey's earliest start date?
A:

Q: Is the candidate open to relocation?
A:
""".strip()


def dedent_block(text: str) -> str:
    return textwrap.dedent(text).strip() + "\n"


def load_text_or_default(path: Path, default_content: str) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8").strip() + "\n"
    return dedent_block(default_content)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent_block(content), encoding="utf-8")


def copy_verified_source_data() -> None:
    if not SOURCE_DATA_FILE.exists():
        raise FileNotFoundError(f"Missing source data file: {SOURCE_DATA_FILE}")
    shutil.copyfile(SOURCE_DATA_FILE, OUTPUT_DIR / "verified_source_data.md")


def convert_markdown_to_docx(markdown_path: Path, docx_path: Path) -> bool:
    if shutil.which("pandoc") is None:
        return False

    command = [
        "pandoc",
        str(markdown_path),
        "-f",
        "gfm",
        "-t",
        "docx",
        "-o",
        str(docx_path),
    ]

    if REFERENCE_DOC_FILE.exists():
        command.extend(["--reference-doc", str(REFERENCE_DOC_FILE)])

    subprocess.run(command, check=True, capture_output=True, text=True)
    return True


def build_global_resume_package() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    screening_answers_content = load_text_or_default(
        SCREENING_ANSWERS_SOURCE_FILE,
        SCREENING_ANSWERS_FALLBACK_CONTENT,
    )
    write_text(OUTPUT_DIR / "README.md", README_CONTENT.format(generated_at=generated_at))
    write_text(OUTPUT_DIR / "global_resume.md", GLOBAL_RESUME_CONTENT)
    write_text(OUTPUT_DIR / "candidate_profile.md", CANDIDATE_PROFILE_CONTENT)
    write_text(OUTPUT_DIR / "application_agent_instructions.md", AGENT_INSTRUCTIONS_CONTENT)
    write_text(OUTPUT_DIR / "screening_answers.md", screening_answers_content)
    copy_verified_source_data()

    markdown_resume = OUTPUT_DIR / "global_resume.md"
    docx_resume = OUTPUT_DIR / "global_resume.docx"
    try:
        created_docx = convert_markdown_to_docx(markdown_resume, docx_resume)
    except subprocess.CalledProcessError:
        created_docx = False

    print(f"Created package in: {OUTPUT_DIR}")
    for file_path in sorted(OUTPUT_DIR.iterdir()):
        print(f"- {file_path.name}")
    print(f"Word export created: {'yes' if created_docx else 'no'}")


if __name__ == "__main__":
    build_global_resume_package()
